# Use root/example as user/password credentials
version: '3.1'

services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
  app:
    build:
      context: "$PWD"
      dockerfile: Dockerfile
    links:
     - "mysql:db"
    ports:
      - 80:80
        #volumes:
        #- ./laravel:/var/www/html
    restart: always
    tty: true
    stdin_open: true
